export enum CMDTYPES {
  SEARCH_MAIN = 'SEARCH_MAIN',
  SEARCH_RESULT = 'SEARCH_RESULT',
  MAIN = 'MAIN',
  JOIN_OTPCERT = 'JOIN_OTPCERT',
  JOIN_TERMS = 'JOIN_TERMS',
  MY_MAIN = 'MY_MAIN',
  PURCHASE_HISTORY = 'PURCHASE_HISTORY',
  PURCHASE_HISTORY_DETAIL = 'PURCHASE_HISTORY_DETAIL',
  PURCHASE_HISTORY_REFUND = 'PURCHASE_HISTORY_REFUND',
  PURCHASE_HISTORY_APPLY_COMPLETE = 'PURCHASE_HISTORY_APPLY_COMPLETE',
  REGISTER_COUPON_MAIN = 'REGISTER_COUPON_MAIN',
  REGISTER_COUPON_SELECT_IMAGE = 'REGISTER_COUPON_SELECT_IMAGE',
}
